In [2]:
import numpy as np
np.__version__

'1.25.2'

# NumPy Arrays Manipulation Basics :

* Attributes:
    * Determining the size, shape, memory consumption, and data types of arrays.
* Indexing:
    * Getting and setting the values of individual array elements
* Slicing:
    * Getting and setting smaller subarrays within a larger array
* Reshaping:
    * Changing the shape of a given array
* Joining and splitting:
    * Combining multiple arrays into one, and splitting one array into many


### A: NP Array Attributes

In [15]:
nprange = np.random.default_rng(seed=42)

arr_1d = nprange.integers(10, size=6) 
arr_2d = nprange.integers(10, size=(3, 4))
arr_3d = nprange.integers(10, size=(3,4,5)) 

print(f"1D array: \n {arr_1d} \n\n 2D array: \n  {arr_2d} \n\n 3D array: \n {arr_3d}")

1D array: 
 [0 7 6 4 4 8] 

 2D array: 
  [[0 6 2 0]
 [5 9 7 7]
 [7 7 5 1]] 

 3D array: 
 [[[8 4 5 3 1]
  [9 7 6 4 8]
  [5 4 4 2 0]
  [5 8 0 8 8]]

 [[2 6 1 7 7]
  [3 0 9 4 8]
  [6 7 7 1 3]
  [4 4 0 5 1]]

 [[7 6 9 7 3]
  [9 4 3 9 3]
  [0 4 7 1 4]
  [1 6 4 3 2]]]


In [16]:
arrs = {'1D-array': arr_1d, '2D-array': arr_2d, '3D-array': arr_3d}

for key, value in arrs.items():
    print(f"{key} --> ndim: {value.ndim}, shape: {value.ndim}, size: {value.size}, dtype: {value.dtype} ")

1D-array --> ndim: 1, shape: 1, size: 6, dtype: int64 
2D-array --> ndim: 2, shape: 2, size: 12, dtype: int64 
3D-array --> ndim: 3, shape: 3, size: 60, dtype: int64 


### B: NP Array Slicing

* $ array[start:stop:step] $

##### B.1: Slicing 1D Subarrays

In [47]:
def slice_1d(array):
    print(f"Original Array : \n\t {array = } \n")
    print(f"First four elements : \n\t {array[:4] = } \n")
    print(f"Elements after index 2(3rd Element) : \n\t {array[2:] = } \n")
    print(f"Accessing Middle Elements(3rd Element to 5th Element) : \n\t {array[2:5] = } \n")
    print(f"Access every second element : \n\t {array[::2] = } \n")
    print(f"Access every second element, starting at index 2 : \n\t {array[2::2] = } \n")
    print(f"Access every second element, starting at index 2 : \n\t {array[2::2] = } \n")
    print(f"Access and reverse all elements : \n\t {array[::-1] = } \n")
    print(f"Access every second element from index 4, reversed : \n\t {array[4::-2] = } \n")

slice_1d(arr_1d)

Original Array : 
	 array = array([0, 7, 6, 4, 4, 8], dtype=int64) 

First four elements : 
	 array[:4] = array([0, 7, 6, 4], dtype=int64) 

Elements after index 2(3rd Element) : 
	 array[2:] = array([6, 4, 4, 8], dtype=int64) 

Accessing Middle Elements(3rd Element to 5th Element) : 
	 array[2:5] = array([6, 4, 4], dtype=int64) 

Access every second element : 
	 array[::2] = array([0, 6, 4], dtype=int64) 

Access every second element, starting at index 2 : 
	 array[2::2] = array([6, 4], dtype=int64) 

Access every second element, starting at index 2 : 
	 array[2::2] = array([6, 4], dtype=int64) 

Access and reverse all elements : 
	 array[::-1] = array([8, 4, 4, 6, 7, 0], dtype=int64) 

Access every second element from index 4, reversed : 
	 array[4::-2] = array([4, 6, 0], dtype=int64) 



##### B.2: Slicing Multidimensional Subarrays

In [80]:
def slice_md(array):
    print(f"Original Array : \n {array} \n")
    print(f"Accessing all rows and the 2nd column : \n array[:, 1] \n {array[:, 1] } \n")
    print(f"Accessing the 3rd row and all columns : \n array[2, :] \n {array[2, :] } \n")
    print(f"Accessing the 3rd row and all columns : \n array[2] \n {array[2] } \n")
    print(f"First 2 rows and 3 columns : \n array[:2, :3] \n {array[:2, :3] } \n")
    print(f"First 3 rows and every 2nd column : \n array[:3, ::2] \n {array[:3, ::2] } \n")
    print(f"Reverse all rows and columns : \n array[::-1, ::-1] \n {array[::-1, ::-1] } \n")

slice_md(arr_2d)

Original Array : 
 [[0 6 2 0]
 [5 9 7 7]
 [7 7 5 1]] 

Accessing all rows and the 2nd column : 
 array[:, 1] 
 [6 9 7] 

Accessing the 3rd row and all columns : 
 array[2, :] 
 [7 7 5 1] 

Accessing the 3rd row and all columns : 
 array[2] 
 [7 7 5 1] 

First 2 rows and 3 columns : 
 array[:2, :3] 
 [[0 6 2]
 [5 9 7]] 

First 3 rows and every 2nd column : 
 array[:3, ::2] 
 [[0 2]
 [5 7]
 [7 5]] 

Reverse all rows and columns : 
 array[::-1, ::-1] 
 [[1 5 7 7]
 [7 7 9 5]
 [0 2 6 0]] 



##### B.3: Subarrays as No-Copy Views

* NumPy array slices are returned as views rather than copies of the array data.

In [81]:
print(arr_2d)

[[0 6 2 0]
 [5 9 7 7]
 [7 7 5 1]]


In [83]:
arr_2d_subarray = arr_2d[1:3, 2:]
print(arr_2d_subarray)

[[7 7]
 [5 1]]


In [85]:
arr_2d_subarray[1, 1] = 1000
print(arr_2d_subarray)

[[   7    7]
 [   5 1000]]


In [86]:
print(arr_2d)

[[   0    6    2    0]
 [   5    9    7    7]
 [   7    7    5 1000]]


##### B.4: Creating Copies of Arrays

In [89]:
arr_2d_subarray_copy = arr_2d[1:3, 2:].copy()
arr_2d_subarray_copy

array([[   7,    7],
       [   5, 1000]], dtype=int64)

In [90]:
arr_2d_subarray_copy[1, 1] = 69
print(arr_2d_subarray_copy)

[[ 7  7]
 [ 5 69]]


In [91]:
print(arr_2d)

[[   0    6    2    0]
 [   5    9    7    7]
 [   7    7    5 1000]]


### C: Reshaping of Arrays

In [97]:
arr_3d_reshape = np.arange(11, 20).reshape(3, 3)
print(arr_3d_reshape)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [109]:
x = np.array([2, 4, 6, 8])
print(x.reshape((1, 4)))

[[2 4 6 8]]


In [103]:
print(x.reshape((4, 1)))

[[2]
 [4]
 [6]
 [8]]


In [104]:
print(x)

[2 4 6 8]


In [110]:
x[np.newaxis, :]

array([[2, 4, 6, 8]])

In [111]:
x[:, np.newaxis]

array([[2],
       [4],
       [6],
       [8]])

### D: Array Concatenation and Splitting


##### D.1: Array Concatenation

* $np.concatenate, np.vstack, np.hstack$
* For higher dimensional arrays, $np.dstack$ will stack arrays along the 3rd axis

In [115]:
a = np.array([1, 3, 5])
b = np.array([20, 40, 60])
np.concatenate([a, b]) 

array([ 1,  3,  5, 20, 40, 60])

In [116]:
np.concatenate([b, a])

array([20, 40, 60,  1,  3,  5])

In [117]:
c = np.array([111, 222, 333])
np.concatenate([a, b, c])

array([  1,   3,   5,  20,  40,  60, 111, 222, 333])

In [124]:
grid1 = np.arange(1, 7).reshape(2, 3)
grid2 = np.arange(101, 107).reshape(2, 3)

In [126]:
np.concatenate([grid1, grid2]) # default axis=0, row-wise concatenation

array([[  1,   2,   3],
       [  4,   5,   6],
       [101, 102, 103],
       [104, 105, 106]])

In [130]:
np.concatenate([grid1, grid2], axis=1) # axis=1, column-wise concatenation

array([[  1,   2,   3, 101, 102, 103],
       [  4,   5,   6, 104, 105, 106]])

In [133]:
# np.vstack, np.hstack for mixed dimensions

np.vstack([a, grid2])

array([[  1,   3,   5],
       [101, 102, 103],
       [104, 105, 106]])

In [137]:
d = np.array([111, 111]).reshape(2, 1)
np.hstack([grid1, d])

array([[  1,   2,   3, 111],
       [  4,   5,   6, 111]])

In [148]:
grid3 = np.arange(1, 10).reshape(3, 3)
e = np.arange(111, 120).reshape(3, 3)
np.dstack([grid3, e])


array([[[  1, 111],
        [  2, 112],
        [  3, 113]],

       [[  4, 114],
        [  5, 115],
        [  6, 116]],

       [[  7, 117],
        [  8, 118],
        [  9, 119]]])

##### D.2: Array Splitting

* $np.split, np.hsplit, np.vsplit$
* For higher-dimensional arrays, $np.dsplit$ will split arrays along the 3rd axis.


In [153]:
x = [1, 2, 3, 69, 69, 69, 111, 121, 131]
x1, x2, x3, x4 = np.split(x, [2, 5, 8])
print(x1, x2, x3, x4)

[1 2] [ 3 69 69] [ 69 111 121] [131]


In [159]:
grid = np.arange(36).reshape(6, 6)
grid

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [162]:
upper, middle, lower = np.vsplit(grid, [2, 4])
print(upper)
print(middle)
print(lower)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [163]:
left, middle, right = np.hsplit(grid, [2, 4])
print(left)
print(middle)
print(right)

[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]
 [30 31]]
[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]
 [26 27]
 [32 33]]
[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]
 [34 35]]
